;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        dabbrev-expand
        evil-backward-char
        evil-backward-word-begin
        evil-delete
        evil-delete-char
        evil-forward-char
        evil-forward-word-begin
        evil-forward-word-end
        evil-mouse-drag-region
        evil-next-line
        evil-previous-line
        highlight-symbol-next
        ))

(setq mc/cmds-to-run-once
      '(
        describe-key
        edebug-step-mode
        evil-emacs-state
        evil-exit-emacs-state
        evil-exit-visual-state
        evil-force-normal-state
        evil-insert
        evil-normal-state
        evil-window-right
        ggtags-navigation-mode-done
        highlight-symbol-query-replace
        read-only-mode
        undefined
        ))
